---


# first ansible-exercise 

- name: Arista Ansible-exercise1
  hosts: arista

  tasks:
    - name: create VLANS
      eos_vlan: name={{ item.vlan_name }} vlanid={{ item.vlan_id }}
            username={{ eapi_username }}
            password={{ eapi_password }}
            host={{ eapi_hostname }}
            port={{ eapi_port }}
            transport=https

      with_items:
        - {vlan_name: red, vlan_id: 221}
        - {vlan_name: blue, vlan_id: 222}
        - {vlan_name: green, vlan_id: 223}


